// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabkIeLRn-JuDS3inaVqR86IgtRPOltiw',
    appId: '1:788743725688:web:f2f31f052335887b11438d',
    messagingSenderId: '788743725688',
    projectId: 'tfggzp',
    authDomain: 'tfggzp.firebaseapp.com',
    databaseURL: 'https://tfggzp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tfggzp.appspot.com',
    measurementId: 'G-0MPEK22E5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMMsPsCjopVrg9-nlHI_x1OUalD_GuBzc',
    appId: '1:788743725688:android:9f57a7bcb4f7321211438d',
    messagingSenderId: '788743725688',
    projectId: 'tfggzp',
    databaseURL: 'https://tfggzp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tfggzp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvcI9gK1SeFFUnjqZ3Yth0AlZ--Xs5uxQ',
    appId: '1:788743725688:ios:19450246912936dc11438d',
    messagingSenderId: '788743725688',
    projectId: 'tfggzp',
    databaseURL: 'https://tfggzp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tfggzp.appspot.com',
    iosClientId: '788743725688-mf81gigd2eskndhdd1hdua4qetb0emqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfggzp',
  );
}
